version: "3"
services:
  client:
    container_name: client
    build: ./client
    image: debug_client
    ports:
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: ["http-server"]
  api:
    container_name: api
    image: node:12.18.4
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=pass
      - PGDATABASE=journal
      - PGPORT=5432
    volumes:
      - type: bind
        source: ./api
        target: /code
    working_dir: /api
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db
  db:
    container_name: journal_db
    image: postgres:12.4
    environment:
      - POSTGRES_DB=journal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/docker-entrypoint-initdb.d/:ro"
volumes:
  dbdata:
networks:
  default:
    name: api
